version: '2'
services:
  alive-checker:
    restart: always
    build: alive-checker
    ports:
      - 3000:3000
    links:
      - parity:node
    depends_on:
      - parity
  parity:
    image: "parity/parity:stable"
    restart: always
    command: --tracing on --warp --port 30303 --jsonrpc-port 8544 --jsonrpc-interface all,-personal,-parity --no-ws --no-dapps --jsonrpc-apis safe --max-peers 60 --cache-size 4096 --jsonrpc-threads 32 --jsonrpc-server-threads 32 --tx-queue-size 131072 --tx-queue-mem-limit 0 --scale-verifiers --jsonrpc-cors all --max-peers 120 --min-peers 60 --no-ws --no-ipc --whisper
    ports:
      - 8544:8544
      - 30303:30303
  nginx:
    image: "nginx"
    restart: always
    links:
      - parity:node
      - alive-checker:checker
    ports:
      - 8545:8545
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
