version: '2'
services:
  alive-checker:
    restart: always
    build: alive-checker
    ports:
      - 3000:3000
    links:
      - parity:node
    depends_on:
      - parity
  parity:
    image: "parity/parity:stable"
    restart: always
    command: --chain ropsten --tracing on --warp --port 30303 --jsonrpc-port 8544 --jsonrpc-interface all --no-ui --no-ws --no-dapps --jsonrpc-apis safe --max-peers 60 --jsonrpc-cors all
    ports:
      - 8544:8544
  nginx:
    image: "nginx"
    restart: always
    links:
      - parity:node
      - alive-checker:checker
    ports:
      - 8545:8545
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
